/***********************************************************************
 * Copyright (c) 2026 The secp256k1 developers                         *
 * Distributed under the MIT software license, see the accompanying    *
 * file COPYING or https://www.opensource.org/licenses/mit-license.php.*
 ***********************************************************************/

#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>

#include "../include/secp256k1.h"

#include "assumptions.h"
#include "util.h"

#include "field_impl.h"
#include "group_impl.h"
#include "ecmult_compute_table_impl.h"
#include "ecdsa_ifma_config.h"
#include "int128_impl.h"

static uint64_t get_bits(const unsigned char *b32, unsigned int offset, unsigned int count) {
    uint64_t ret = 0;
    unsigned int i;
    for (i = 0; i < count; i++) {
        unsigned int bit = offset + i;
        ret |= (uint64_t)((b32[31 - (bit >> 3)] >> (bit & 7)) & 1U) << i;
    }
    return ret;
}

static void fe_to_limbs(uint64_t limbs[5], secp256k1_fe *fe) {
    unsigned char b32[32];
    int i;
    secp256k1_fe_normalize_var(fe);
    secp256k1_fe_get_b32(b32, fe);
    for (i = 0; i < 4; i++) {
        limbs[i] = get_bits(b32, 52U * (unsigned int)i, 52);
    }
    limbs[4] = get_bits(b32, 208, 48);
}

static void print_vector(FILE *fp, const char *name, const uint64_t limbs[5]) {
    int i;
    fprintf(fp, "const uint64_t %s[5] = {\n    ", name);
    for (i = 0; i < 5; i++) {
        fprintf(fp, "UINT64_C(0x%013" PRIx64 ")%s", limbs[i], i == 4 ? "\n" : ", ");
    }
    fprintf(fp, "};\n\n");
}

static void print_table(FILE *fp, const char *name, uint64_t table[5][SECP256K1_ECDSA_IFMA_JOINT_TABLE]) {
    int limb;
    int entry;
    fprintf(fp, "const uint64_t %s[5][SECP256K1_ECDSA_IFMA_JOINT_TABLE] = {\n", name);
    for (limb = 0; limb < 5; limb++) {
        fprintf(fp, "    {\n");
        for (entry = 0; entry < SECP256K1_ECDSA_IFMA_JOINT_TABLE; entry++) {
            const char *suffix;
            if ((entry & 3) == 0) {
                fprintf(fp, "        ");
            }
            suffix = entry == SECP256K1_ECDSA_IFMA_JOINT_TABLE - 1 ? "\n" : ((entry & 3) == 3 ? ",\n" : ", ");
            fprintf(fp, "UINT64_C(0x%013" PRIx64 ")%s", table[limb][entry], suffix);
        }
        fprintf(fp, "    }%s\n", limb == 4 ? "" : ",");
    }
    fprintf(fp, "};\n\n");
}

int main(void) {
    const char outfile[] = "src/precomputed_ecdsa_ifma.c";
    secp256k1_ge_storage storage[SECP256K1_ECDSA_IFMA_Q_TABLE];
    secp256k1_ge fixed[SECP256K1_ECDSA_IFMA_Q_TABLE];
    secp256k1_ge fixed_phi[SECP256K1_ECDSA_IFMA_Q_TABLE];
    uint64_t gx[5], gy[5], gphix[5], gphiy[5];
    uint64_t joint_x[5][SECP256K1_ECDSA_IFMA_JOINT_TABLE];
    uint64_t joint_y[5][SECP256K1_ECDSA_IFMA_JOINT_TABLE];
    secp256k1_gej generator;
    FILE *fp;
    int i;
    int relative_neg;
    int a;
    int b;

    secp256k1_gej_set_ge(&generator, &secp256k1_ge_const_g);
    secp256k1_ecmult_compute_table(storage, 5, &generator);
    for (i = 0; i < SECP256K1_ECDSA_IFMA_Q_TABLE; i++) {
        secp256k1_ge_from_storage(&fixed[i], &storage[i]);
        secp256k1_ge_mul_lambda(&fixed_phi[i], &fixed[i]);
    }
    fe_to_limbs(gx, &fixed[0].x);
    fe_to_limbs(gy, &fixed[0].y);
    fe_to_limbs(gphix, &fixed_phi[0].x);
    fe_to_limbs(gphiy, &fixed_phi[0].y);
    /* Overall negation is applied during lookup, so only the relative sign is stored. */
    for (relative_neg = 0; relative_neg < 2; relative_neg++) {
        for (a = 0; a < SECP256K1_ECDSA_IFMA_Q_TABLE; a++) {
            for (b = 0; b < SECP256K1_ECDSA_IFMA_Q_TABLE; b++) {
                secp256k1_ge second = fixed_phi[b];
                secp256k1_ge sum;
                secp256k1_gej sumj;
                uint64_t x[5], y[5];
                int limb;
                int index = (relative_neg * SECP256K1_ECDSA_IFMA_Q_TABLE + a) * SECP256K1_ECDSA_IFMA_Q_TABLE + b;
                if (relative_neg) {
                    secp256k1_ge_neg(&second, &second);
                }
                secp256k1_gej_set_ge(&sumj, &fixed[a]);
                secp256k1_gej_add_ge_var(&sumj, &sumj, &second, NULL);
                CHECK(!secp256k1_gej_is_infinity(&sumj));
                secp256k1_ge_set_gej_var(&sum, &sumj);
                fe_to_limbs(x, &sum.x);
                fe_to_limbs(y, &sum.y);
                for (limb = 0; limb < 5; limb++) {
                    joint_x[limb][index] = x[limb];
                    joint_y[limb][index] = y[limb];
                }
            }
        }
    }

    fp = fopen(outfile, "w");
    if (fp == NULL) {
        fprintf(stderr, "Could not open %s for writing!\n", outfile);
        return EXIT_FAILURE;
    }
    fprintf(fp, "/* This file was automatically generated by precompute_ecdsa_ifma. */\n");
    fprintf(fp, "#include \"util.h\"\n");
    fprintf(fp, "#include \"ecdsa_ifma_config.h\"\n");
    fprintf(fp, "#ifdef SECP256K1_ECDSA_VERIFY_MANY_IFMA\n");
    fprintf(fp, "#include \"precomputed_ecdsa_ifma.h\"\n\n");
    print_vector(fp, "secp256k1_ecdsa_ifma_gx", gx);
    print_vector(fp, "secp256k1_ecdsa_ifma_gy", gy);
    print_vector(fp, "secp256k1_ecdsa_ifma_gphix", gphix);
    print_vector(fp, "secp256k1_ecdsa_ifma_gphiy", gphiy);
    print_table(fp, "secp256k1_ecdsa_ifma_joint_x", joint_x);
    print_table(fp, "secp256k1_ecdsa_ifma_joint_y", joint_y);
    fprintf(fp, "#endif /* SECP256K1_ECDSA_VERIFY_MANY_IFMA */\n");
    fclose(fp);
    return EXIT_SUCCESS;
}
